version: '3.9'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: telotimeless
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: 
      unless-stopped

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - ./media:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: telotimeless
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
    restart: 
     unless-stopped
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000/api
    restart: 
     unless-stopped

volumes:
  postgres_data:
