# Generated by Django 5.2.3 on 2025-07-04 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_hospital_slug_hospital_title_hospitalnews'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='category',
            field=models.CharField(choices=[('plastic', 'Plastic Surgery'), ('derma', 'Dermatology'), ('hospital', 'Hospital')], default='plastic', max_length=50),
        ),
        migrations.AddField(
            model_name='hospital',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='description_ko',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='name_ko',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='summary',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='hospital',
            name='summary_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='summary_ko',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='title_ko',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hospitalnews',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hospitalnews',
            name='title_ko',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
