# Generated by Django 5.2.3 on 2025-07-04 07:57

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_hospital_category_hospital_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='description',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='description_en',
            field=markdownx.models.MarkdownxField(null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='description_ko',
            field=markdownx.models.MarkdownxField(null=True),
        ),
    ]
