# Generated by Django 5.2.3 on 2025-07-04 08:03

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0004_alter_hospital_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='description_ko',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
